site_name: Alshamali System Design Notes
site_description: An encyclopedia-style guide on system design and software architecture.

theme:
  name: material
  palette:
    # Light mode configuration
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode configuration
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - navigation.sections    # Grouping sections in the sidebar cleanly
  - navigation.expand      # Automatically expands navigation trees
  - navigation.instant
  - navigation.prune
  - search.suggest         # As-you-type search suggestions
  - search.highlight       # Highlight searched terms on the page

extra:
  analytics:
    provider: google
    property: G-69FMV7V3KQ

markdown_extensions:
  - admonition               # For custom warning/info callout boxes
  - pymdownx.details         # For collapsible content blocks
  - pymdownx.superfences     # Superior parsing for complex code blocks / diagrams
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true        # Adds clickable anchor links to headers
      toc_depth: 3           # Restricts TOC depth to improve screen reader flow

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

hooks:
  - hooks.py

plugins:
  - search
  - awesome-pages