name: Deploy Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Pinning to 3.11 or 3.12 is safer than 3.x, which grabs bleeding-edge versions
          python-version: '3.12'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ github.sha }}
          path: .cache
          
      - name: Install MkDocs Material & Dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-minify-plugin
          pip install beautifulsoup4
        
      - name: Build and Deploy to gh-pages branch
        run: mkdocs gh-deploy --force
